name: Hello World CI (Mac Self-Hosted)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: self-hosted   # ✅ Use our Mac runner

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install -r requirements.txt

      - name: Run tests
        run: pytest -v
