name: Python App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: [self-hosted, linux, arm64]  # Adjust labels to match your Pi runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Match your Pi's Python version

      - name: Create virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run script
        run: |
          source venv/bin/activate
          python your_script.py
